spring.application.name=EcoembesServerG10
spring.output.ansi.enabled=ALWAYS

server.port=8080

# H2 database configuration
spring.datasource.url=jdbc:h2:file:./data/ecoembesdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=ecoembes
spring.datasource.password=ecoembes

spring.sql.init.platform=h2

# Enable H2 console in the browser
spring.h2.console.enabled=true

# Auto-generate the database schema based on the entities
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false